/* THIS FILE IS GENERATED BY BUILD TOOLS! DO NOT TOUCH! DO NOT COMMIT! */

#include <nuttx/config.h>
#include <sys/types.h>
#include "connector.h"

extern struct ts_connector kii;

struct ts_connector *ts_connectors[] = {
        &kii,
        NULL,
};
